### ISSUE TITLE
Anomaly global environment cannot be accesed during parsing

### ISSUE THREAD

**Issue by TDiazT** [math-comp/math-comp#347] opened 2019-05-17 19:41 UTC
I was doing some things and came up with this error message:
```
Toplevel input, characters 14-15:
Error: Anomaly "The global environment cannot be accessed during parsing." Please report at http://coq.inria.fr/bugs/.
```

I tried replicating it with a simpler case, and came up with the following (maybe there is a simpler way haha, but well).

```
From mathcomp Require Import all_ssreflect.
Unset Strict Implicit.
Unset Printing Implicit Defensive.
Set Asymmetric Patterns.


Section Test.

  Variable (p : Prop).

  Goal p = false -> true.
    move=> H.
    have H2/negbT.

End Test.
```

Working with coq 8.8.1, ssreflect 1.7

**Comment by TDiazT** [comment] 2019-05-17 19:44
Oh yeah, actually I added extra things 😆. You just need to do : 
```
From mathcomp Require Import all_ssreflect.
Unset Strict Implicit.
Unset Printing Implicit Defensive.
Set Asymmetric Patterns.


Section Test.

  Variable (p : Prop).

  Goal p. 
    have H/negbT.

End Test.
```

**Comment by anton-trunov** [comment] 2019-05-17 19:52
It seems this issue better be moved to Coq's GitHub, as the same anomaly can be reproduced with the following (silly) snippet:
```coq
From Coq Require Import ssreflect.

Goal True.
have H/H.
```

(tried on Coq 8.10+alpha, commit f913913a6a1b1e01d154d0c9af3b3807459b0b9f)

**Comment by pi8027** [comment] 2020-07-15 18:48
FYI, this issue has now been reported as coq/coq#12695.

**Comment by pi8027** [comment] 2020-09-09 23:48
Since an issue has been opened on the Coq side, I think we can close it here.

**Closed by pi8027** 2020-09-09 23:48 UTC
Labels: kind: coq ↝
