### ISSUE TITLE
Anonymous EVars are no longer named; breaks build.

### ISSUE THREAD

**Issue by spacekitteh** [math-comp/math-comp#27] opened 2016-02-16 22:11 UTC
File "./ssreflect/ssrnat.v", line 213, characters 7-56:
Anomaly: Evar ?X79 was not declared. Please report.
Makefile.coq:558: recipe for target 'ssreflect/ssrnat.vo' failed
make[1]: **\* [ssreflect/ssrnat.vo] Error 129
Makefile:24: recipe for target 'all' failed
make: **\* [all] Error 2

See: https://github.com/coq/coq/commit/f46a5686853353f8de733ae7fbd21a3a61977bc7

**Comment by gares** [comment] 2016-02-17 07:21
Hello, of which  version of Coq are you talking about?  According to our regression testing
    http://ssr.msr-inria.inria.fr/hudson/
version 8.5 works fine.

**Comment by gares** [comment] 2016-02-17 09:28
And the version for trunk does not even compile.  I guess you managed to get the right commit of Coq and Ssreflect so that thins compile and there you experienced the Anomaly. So I guess there is a real bug but unfortunately I don't know how to reproduce it (i.e. no jenkins build failed because of the error you report).  It will surely pop up again when the compilation on trunk is fixed.

**Comment by CohenCyril** [comment] 2019-04-04 17:58
According to CI this bug never does not happen. I close the issue. Feel free to reopen if needed.

**Closed by CohenCyril** 2019-04-04 17:58 UTC
Labels: kind: bug
